"""init

Revision ID: 994c7522912e
Revises: 
Create Date: 2026-04-12 17:35:13.354125

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '994c7522912e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('cuisine', 'venue', 'specialty', name='category_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_categories_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_categories_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_categories_type'), ['type'], unique=False)

    op.create_table('cities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), server_default=sa.text("'US'"), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities'))
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index('ix_cities_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_cities_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_cities_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_cities_geo', ['lat', 'lng'], unique=False)
        batch_op.create_index('ix_cities_slug', ['slug'], unique=False)

    op.create_table('enrichment_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrichment_jobs')),
    sa.UniqueConstraint('place_id', 'job_type', 'is_active', name='uq_active_job_per_place_type')
    )
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_locked_at'), ['locked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_enrichment_locked', ['locked_at'], unique=False)
        batch_op.create_index('ix_enrichment_next_run', ['next_run_at'], unique=False)
        batch_op.create_index('ix_enrichment_place_type', ['place_id', 'job_type'], unique=False)
        batch_op.create_index('ix_enrichment_ready', ['status', 'next_run_at', 'priority'], unique=False)
        batch_op.create_index('ix_enrichment_status_priority', ['status', 'priority'], unique=False)

    op.create_table('discovery_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('category_hint', sa.String(length=80), nullable=True),
    sa.Column('confidence_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='candidate', nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved_place_id', sa.String(length=36), nullable=True),
    sa.Column('blocked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_discovery_candidates_city_id_cities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_candidates')),
    sa.UniqueConstraint('city_id', 'name', 'lat', 'lng', name='uq_candidate_city_name_location'),
    sa.UniqueConstraint('external_id', 'source', name='uq_candidate_external_source')
    )
    with op.batch_alter_table('discovery_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_category', ['category_id'], unique=False)
        batch_op.create_index('ix_candidate_city', ['city_id'], unique=False)
        batch_op.create_index('ix_candidate_confidence', ['confidence_score'], unique=False)
        batch_op.create_index('ix_candidate_external_id', ['external_id'], unique=False)
        batch_op.create_index('ix_candidate_lat', ['lat'], unique=False)
        batch_op.create_index('ix_candidate_lng', ['lng'], unique=False)
        batch_op.create_index('ix_candidate_promote', ['confidence_score', 'status'], unique=False)
        batch_op.create_index('ix_candidate_resolved', ['resolved', 'blocked'], unique=False)
        batch_op.create_index('ix_candidate_source', ['source'], unique=False)
        batch_op.create_index('ix_candidate_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_blocked'), ['blocked'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_category_hint'), ['category_hint'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_confidence_score'), ['confidence_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_promoted_at'), ['promoted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_resolved_place_id'), ['resolved_place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_candidates_discovery_candidates_status'), ['status'], unique=False)

    op.create_table('places',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city_id', sa.String(length=36), nullable=False),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('price_tier', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('master_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('confidence_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('operational_confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('local_validation', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('hype_penalty', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('rank_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('has_menu', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_menu_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_version', sa.Integer(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_recompute', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_places_city_id_cities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places')),
    sa.UniqueConstraint('city_id', 'name', name='uq_places_city_name')
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index('ix_places_city_active', ['city_id', 'is_active'], unique=False)
        batch_op.create_index('ix_places_city_rank_id', ['city_id', 'rank_score', 'id'], unique=False)
        batch_op.create_index('ix_places_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_places_geo', ['lat', 'lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_has_menu'), ['has_menu'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_lng'), ['lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_master_score'), ['master_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_needs_recompute'), ['needs_recompute'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_price_tier'), ['price_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_rank_score'), ['rank_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_places_website'), ['website'], unique=False)
        batch_op.create_index('ix_places_price_tier', ['price_tier'], unique=False)
        batch_op.create_index('ix_places_website', ['website'], unique=False)

    op.create_table('city_place_rankings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('city_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_city_place_rankings_city_id_cities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_city_place_rankings_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city_place_rankings')),
    sa.UniqueConstraint('city_id', 'place_id', name='uq_city_place_ranking_city_place')
    )
    with op.batch_alter_table('city_place_rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_place_rankings_city_place_rankings_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_city_place_rankings_city_place_rankings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_city_place_rankings_city_place_rankings_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_city_place_rankings_city_place_rankings_rank_position'), ['rank_position'], unique=False)
        batch_op.create_index(batch_op.f('ix_city_place_rankings_city_place_rankings_rank_score'), ['rank_score'], unique=False)
        batch_op.create_index('ix_city_place_rankings_city_rank', ['city_id', 'rank_position'], unique=False)
        batch_op.create_index('ix_city_place_rankings_created', ['created_at'], unique=False)
        batch_op.create_index('ix_city_place_rankings_score', ['city_id', 'rank_score'], unique=False)

    op.create_table('menu_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('source_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_menu_items_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items')),
    sa.UniqueConstraint('place_id', 'name', 'category', name='uq_menu_place_name_category')
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_index('ix_menu_active', ['is_active'], unique=False)
        batch_op.create_index('ix_menu_category', ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_menu_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_menu_items_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_menu_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_menu_items_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_menu_items_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_menu_items_source_snapshot_id'), ['source_snapshot_id'], unique=False)
        batch_op.create_index('ix_menu_place', ['place_id'], unique=False)
        batch_op.create_index('ix_menu_place_active', ['place_id', 'is_active'], unique=False)
        batch_op.create_index('ix_menu_place_created', ['place_id', 'created_at'], unique=False)
        batch_op.create_index('ix_menu_price', ['price'], unique=False)
        batch_op.create_index('ix_menu_snapshot', ['source_snapshot_id'], unique=False)

    op.create_table('menu_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('item_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('normalized_items', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('extractor_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_menu_snapshots_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_snapshots'))
    )
    with op.batch_alter_table('menu_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_menu_snapshots_lookup', ['place_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_snapshots_menu_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_snapshots_menu_snapshots_extraction_method'), ['extraction_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_snapshots_menu_snapshots_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_snapshots_menu_snapshots_success'), ['success'], unique=False)
        batch_op.create_index('ix_menu_snapshots_method', ['extraction_method'], unique=False)
        batch_op.create_index('ix_menu_snapshots_place_created', ['place_id', 'created_at'], unique=False)
        batch_op.create_index('ix_menu_snapshots_source_url', ['source_url'], unique=False)
        batch_op.create_index('ix_menu_snapshots_success', ['success'], unique=False)

    op.create_table('menu_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), server_default='website', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_menu_sources_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_sources')),
    sa.UniqueConstraint('place_id', 'source_hash', name='uq_menu_source_place_hash')
    )
    with op.batch_alter_table('menu_sources', schema=None) as batch_op:
        batch_op.create_index('ix_menu_source_active', ['is_active'], unique=False)
        batch_op.create_index('ix_menu_source_last_seen', ['last_seen_at'], unique=False)
        batch_op.create_index('ix_menu_source_place_id', ['place_id'], unique=False)
        batch_op.create_index('ix_menu_source_type', ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_sources_menu_sources_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_sources_menu_sources_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_sources_menu_sources_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_sources_menu_sources_source_hash'), ['source_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_sources_menu_sources_source_type'), ['source_type'], unique=False)

    op.create_table('place_categories',
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_place_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_categories_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'category_id', name=op.f('pk_place_categories'))
    )
    with op.batch_alter_table('place_categories', schema=None) as batch_op:
        batch_op.create_index('ix_place_categories_category', ['category_id'], unique=False)
        batch_op.create_index('ix_place_categories_place', ['place_id'], unique=False)

    op.create_table('place_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('claim_key', sa.String(length=128), server_default=sa.text("('')"), nullable=False),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('(0.5)'), nullable=False),
    sa.Column('weight', sa.Float(), server_default=sa.text('(1.0)'), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('is_verified_source', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_user_submitted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(value_text IS NOT NULL) OR (value_number IS NOT NULL) OR (value_json IS NOT NULL)', name=op.f('ck_place_claims_ck_place_claim_has_value')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_claims_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_claims')),
    sa.UniqueConstraint('place_id', 'field', 'claim_key', name='uq_place_claim_place_field_key')
    )
    with op.batch_alter_table('place_claims', schema=None) as batch_op:
        batch_op.create_index('ix_claim_place_confidence', ['place_id', 'confidence'], unique=False)
        batch_op.create_index('ix_claim_place_field', ['place_id', 'field'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_claims_place_claims_claim_key'), ['claim_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_claims_place_claims_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_claims_place_claims_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_claims_place_claims_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_claims_place_claims_source'), ['source'], unique=False)

    op.create_table('place_feed_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_feed_snapshots_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_feed_snapshots'))
    )
    with op.batch_alter_table('place_feed_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_source'), ['source'], unique=False)
        batch_op.create_index('ix_snapshot_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_snapshot_external', ['external_id'], unique=False)
        batch_op.create_index('ix_snapshot_lookup', ['place_id', 'source', 'created_at'], unique=False)
        batch_op.create_index('ix_snapshot_place_id', ['place_id'], unique=False)
        batch_op.create_index('ix_snapshot_source', ['source'], unique=False)

    op.create_table('place_image_fetch_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_image_fetch_logs_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_image_fetch_logs'))
    )
    with op.batch_alter_table('place_image_fetch_logs', schema=None) as batch_op:
        batch_op.create_index('ix_img_fetch_place', ['place_id'], unique=False)
        batch_op.create_index('ix_img_fetch_place_source_time', ['place_id', 'source', 'fetched_at'], unique=False)
        batch_op.create_index('ix_img_fetch_source', ['source'], unique=False)
        batch_op.create_index('ix_img_fetch_time', ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_image_fetch_logs_place_image_fetch_logs_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_image_fetch_logs_place_image_fetch_logs_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_image_fetch_logs_place_image_fetch_logs_source'), ['source'], unique=False)

    op.create_table('place_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('(0.5)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_images_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_images'))
    )
    with op.batch_alter_table('place_images', schema=None) as batch_op:
        batch_op.create_index('ix_place_images_confidence', ['confidence'], unique=False)
        batch_op.create_index('ix_place_images_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_images_place_images_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_images_place_images_is_primary'), ['is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_images_place_images_place_id'), ['place_id'], unique=False)
        batch_op.create_index('ix_place_images_place_primary', ['place_id', 'is_primary'], unique=False)
        batch_op.create_index('uq_place_image_place_url', ['place_id', 'url'], unique=True)

    op.create_table('place_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('raw_value', sa.String(length=255), nullable=True),
    sa.Column('external_event_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_signals_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_signals')),
    sa.UniqueConstraint('place_id', 'provider', 'signal_type', 'external_event_id', name='uq_place_signal_dedupe')
    )
    with op.batch_alter_table('place_signals', schema=None) as batch_op:
        batch_op.create_index('ix_place_signals_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_place_signals_place_id', ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_signals_place_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_signals_place_signals_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_signals_place_signals_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_signals_place_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index('ix_place_signals_provider', ['provider'], unique=False)
        batch_op.create_index('ix_place_signals_type', ['signal_type'], unique=False)

    op.create_table('place_truths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('truth_type', sa.String(length=128), nullable=False),
    sa.Column('truth_value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved_from', sa.String(length=512), nullable=True),
    sa.Column('resolver_version', sa.String(length=32), server_default='v2', nullable=False),
    sa.Column('sources_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_truths_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_truths')),
    sa.UniqueConstraint('place_id', 'truth_type', name='uq_place_truth_place_type')
    )
    with op.batch_alter_table('place_truths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_truths_place_truths_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_truths_place_truths_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_truths_place_truths_truth_type'), ['truth_type'], unique=False)
        batch_op.create_index('ix_truth_confidence', ['confidence'], unique=False)
        batch_op.create_index('ix_truth_place', ['place_id'], unique=False)
        batch_op.create_index('ix_truth_type', ['truth_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_truths', schema=None) as batch_op:
        batch_op.drop_index('ix_truth_type')
        batch_op.drop_index('ix_truth_place')
        batch_op.drop_index('ix_truth_confidence')
        batch_op.drop_index(batch_op.f('ix_place_truths_place_truths_truth_type'))
        batch_op.drop_index(batch_op.f('ix_place_truths_place_truths_place_id'))
        batch_op.drop_index(batch_op.f('ix_place_truths_place_truths_confidence'))

    op.drop_table('place_truths')
    with op.batch_alter_table('place_signals', schema=None) as batch_op:
        batch_op.drop_index('ix_place_signals_type')
        batch_op.drop_index('ix_place_signals_provider')
        batch_op.drop_index(batch_op.f('ix_place_signals_place_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_place_signals_place_signals_provider'))
        batch_op.drop_index(batch_op.f('ix_place_signals_place_signals_place_id'))
        batch_op.drop_index(batch_op.f('ix_place_signals_place_signals_created_at'))
        batch_op.drop_index('ix_place_signals_place_id')
        batch_op.drop_index('ix_place_signals_created_at')

    op.drop_table('place_signals')
    with op.batch_alter_table('place_images', schema=None) as batch_op:
        batch_op.drop_index('uq_place_image_place_url')
        batch_op.drop_index('ix_place_images_place_primary')
        batch_op.drop_index(batch_op.f('ix_place_images_place_images_place_id'))
        batch_op.drop_index(batch_op.f('ix_place_images_place_images_is_primary'))
        batch_op.drop_index(batch_op.f('ix_place_images_place_images_confidence'))
        batch_op.drop_index('ix_place_images_created')
        batch_op.drop_index('ix_place_images_confidence')

    op.drop_table('place_images')
    with op.batch_alter_table('place_image_fetch_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_place_image_fetch_logs_place_image_fetch_logs_source'))
        batch_op.drop_index(batch_op.f('ix_place_image_fetch_logs_place_image_fetch_logs_place_id'))
        batch_op.drop_index(batch_op.f('ix_place_image_fetch_logs_place_image_fetch_logs_fetched_at'))
        batch_op.drop_index('ix_img_fetch_time')
        batch_op.drop_index('ix_img_fetch_source')
        batch_op.drop_index('ix_img_fetch_place_source_time')
        batch_op.drop_index('ix_img_fetch_place')

    op.drop_table('place_image_fetch_logs')
    with op.batch_alter_table('place_feed_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_source')
        batch_op.drop_index('ix_snapshot_place_id')
        batch_op.drop_index('ix_snapshot_lookup')
        batch_op.drop_index('ix_snapshot_external')
        batch_op.drop_index('ix_snapshot_created_at')
        batch_op.drop_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_source'))
        batch_op.drop_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_place_id'))
        batch_op.drop_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_is_active'))
        batch_op.drop_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_external_id'))
        batch_op.drop_index(batch_op.f('ix_place_feed_snapshots_place_feed_snapshots_created_at'))

    op.drop_table('place_feed_snapshots')
    with op.batch_alter_table('place_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_place_claims_place_claims_source'))
        batch_op.drop_index(batch_op.f('ix_place_claims_place_claims_place_id'))
        batch_op.drop_index(batch_op.f('ix_place_claims_place_claims_field'))
        batch_op.drop_index(batch_op.f('ix_place_claims_place_claims_confidence'))
        batch_op.drop_index(batch_op.f('ix_place_claims_place_claims_claim_key'))
        batch_op.drop_index('ix_claim_place_field')
        batch_op.drop_index('ix_claim_place_confidence')

    op.drop_table('place_claims')
    with op.batch_alter_table('place_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_place_categories_place')
        batch_op.drop_index('ix_place_categories_category')

    op.drop_table('place_categories')
    with op.batch_alter_table('menu_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_sources_menu_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_menu_sources_menu_sources_source_hash'))
        batch_op.drop_index(batch_op.f('ix_menu_sources_menu_sources_place_id'))
        batch_op.drop_index(batch_op.f('ix_menu_sources_menu_sources_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_menu_sources_menu_sources_is_active'))
        batch_op.drop_index('ix_menu_source_type')
        batch_op.drop_index('ix_menu_source_place_id')
        batch_op.drop_index('ix_menu_source_last_seen')
        batch_op.drop_index('ix_menu_source_active')

    op.drop_table('menu_sources')
    with op.batch_alter_table('menu_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_snapshots_success')
        batch_op.drop_index('ix_menu_snapshots_source_url')
        batch_op.drop_index('ix_menu_snapshots_place_created')
        batch_op.drop_index('ix_menu_snapshots_method')
        batch_op.drop_index(batch_op.f('ix_menu_snapshots_menu_snapshots_success'))
        batch_op.drop_index(batch_op.f('ix_menu_snapshots_menu_snapshots_place_id'))
        batch_op.drop_index(batch_op.f('ix_menu_snapshots_menu_snapshots_extraction_method'))
        batch_op.drop_index(batch_op.f('ix_menu_snapshots_menu_snapshots_created_at'))
        batch_op.drop_index('ix_menu_snapshots_lookup')

    op.drop_table('menu_snapshots')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_snapshot')
        batch_op.drop_index('ix_menu_price')
        batch_op.drop_index('ix_menu_place_created')
        batch_op.drop_index('ix_menu_place_active')
        batch_op.drop_index('ix_menu_place')
        batch_op.drop_index(batch_op.f('ix_menu_items_menu_items_source_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_menu_items_price'))
        batch_op.drop_index(batch_op.f('ix_menu_items_menu_items_place_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_menu_items_name'))
        batch_op.drop_index(batch_op.f('ix_menu_items_menu_items_is_active'))
        batch_op.drop_index(batch_op.f('ix_menu_items_menu_items_category'))
        batch_op.drop_index('ix_menu_category')
        batch_op.drop_index('ix_menu_active')

    op.drop_table('menu_items')
    with op.batch_alter_table('city_place_rankings', schema=None) as batch_op:
        batch_op.drop_index('ix_city_place_rankings_score')
        batch_op.drop_index('ix_city_place_rankings_created')
        batch_op.drop_index('ix_city_place_rankings_city_rank')
        batch_op.drop_index(batch_op.f('ix_city_place_rankings_city_place_rankings_rank_score'))
        batch_op.drop_index(batch_op.f('ix_city_place_rankings_city_place_rankings_rank_position'))
        batch_op.drop_index(batch_op.f('ix_city_place_rankings_city_place_rankings_place_id'))
        batch_op.drop_index(batch_op.f('ix_city_place_rankings_city_place_rankings_created_at'))
        batch_op.drop_index(batch_op.f('ix_city_place_rankings_city_place_rankings_city_id'))

    op.drop_table('city_place_rankings')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index('ix_places_website')
        batch_op.drop_index('ix_places_price_tier')
        batch_op.drop_index(batch_op.f('ix_places_places_website'))
        batch_op.drop_index(batch_op.f('ix_places_places_rank_score'))
        batch_op.drop_index(batch_op.f('ix_places_places_price_tier'))
        batch_op.drop_index(batch_op.f('ix_places_places_needs_recompute'))
        batch_op.drop_index(batch_op.f('ix_places_places_name'))
        batch_op.drop_index(batch_op.f('ix_places_places_master_score'))
        batch_op.drop_index(batch_op.f('ix_places_places_lng'))
        batch_op.drop_index(batch_op.f('ix_places_places_lat'))
        batch_op.drop_index(batch_op.f('ix_places_places_is_active'))
        batch_op.drop_index(batch_op.f('ix_places_places_has_menu'))
        batch_op.drop_index(batch_op.f('ix_places_places_city_id'))
        batch_op.drop_index('ix_places_geo')
        batch_op.drop_index('ix_places_created_at')
        batch_op.drop_index('ix_places_city_rank_id')
        batch_op.drop_index('ix_places_city_active')

    op.drop_table('places')
    with op.batch_alter_table('discovery_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_source'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_resolved_place_id'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_resolved'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_promoted_at'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_name'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_external_id'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_confidence_score'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_city_id'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_category_id'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_category_hint'))
        batch_op.drop_index(batch_op.f('ix_discovery_candidates_discovery_candidates_blocked'))
        batch_op.drop_index('ix_candidate_status')
        batch_op.drop_index('ix_candidate_source')
        batch_op.drop_index('ix_candidate_resolved')
        batch_op.drop_index('ix_candidate_promote')
        batch_op.drop_index('ix_candidate_lng')
        batch_op.drop_index('ix_candidate_lat')
        batch_op.drop_index('ix_candidate_external_id')
        batch_op.drop_index('ix_candidate_confidence')
        batch_op.drop_index('ix_candidate_city')
        batch_op.drop_index('ix_candidate_category')

    op.drop_table('discovery_candidates')
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_enrichment_status_priority')
        batch_op.drop_index('ix_enrichment_ready')
        batch_op.drop_index('ix_enrichment_place_type')
        batch_op.drop_index('ix_enrichment_next_run')
        batch_op.drop_index('ix_enrichment_locked')
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_priority'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_place_id'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_locked_at'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_enrichment_jobs_is_active'))

    op.drop_table('enrichment_jobs')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('ix_cities_slug')
        batch_op.drop_index('ix_cities_geo')
        batch_op.drop_index(batch_op.f('ix_cities_cities_slug'))
        batch_op.drop_index(batch_op.f('ix_cities_cities_is_active'))
        batch_op.drop_index('ix_cities_active')

    op.drop_table('cities')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_categories_type'))
        batch_op.drop_index(batch_op.f('ix_categories_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_categories_is_active'))

    op.drop_table('categories')
    # ### end Alembic commands ###