"""add_hitlist_tables

Revision ID: e0c588405366
Revises: a3f1b2c4d5e6
Create Date: 2026-04-13 23:17:23.382337

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e0c588405366'
down_revision = 'a3f1b2c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hitlist_dedup_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hitlist_dedup_keys')),
    sa.UniqueConstraint('user_id', 'dedup_key', name='uq_hitlist_dedup_keys_user_key')
    )
    with op.batch_alter_table('hitlist_dedup_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hitlist_dedup_keys_hitlist_dedup_keys_user_id'), ['user_id'], unique=False)

    op.create_table('hitlist_saves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('place_name', sa.String(length=256), nullable=False),
    sa.Column('source_platform', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('place_id', sa.String(length=36), nullable=True),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_hitlist_saves_place_id_places'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hitlist_saves')),
    sa.UniqueConstraint('user_id', 'dedup_key', name='uq_hitlist_saves_user_dedup')
    )
    with op.batch_alter_table('hitlist_saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hitlist_saves_hitlist_saves_resolution_status'), ['resolution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hitlist_saves_hitlist_saves_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_hitlist_saves_place_id', ['place_id'], unique=False)
        batch_op.create_index('ix_hitlist_saves_status', ['resolution_status'], unique=False)
        batch_op.create_index('ix_hitlist_saves_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('hitlist_suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('place_name', sa.String(length=256), nullable=False),
    sa.Column('city_hint', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_platform', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('resolved_place_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_place_id'], ['places.id'], name=op.f('fk_hitlist_suggestions_resolved_place_id_places'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hitlist_suggestions'))
    )
    with op.batch_alter_table('hitlist_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hitlist_suggestions_hitlist_suggestions_place_name'), ['place_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hitlist_suggestions_hitlist_suggestions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_hitlist_suggestions_name_city', ['place_name', 'city_hint'], unique=False)
        batch_op.create_index('ix_hitlist_suggestions_resolved_place', ['resolved_place_id'], unique=False)
        batch_op.create_index('ix_hitlist_suggestions_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_active_job_per_place_type'), sqlite_where=sa.text('is_active = 1'))
        batch_op.create_unique_constraint('uq_active_job_per_place_type', ['place_id', 'job_type', 'is_active'])

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_places_grubhub_url'))
        batch_op.create_index(batch_op.f('ix_places_places_grubhub_url'), ['grubhub_url'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_places_places_grubhub_url'))
        batch_op.create_index(batch_op.f('ix_places_grubhub_url'), ['grubhub_url'], unique=False)

    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_active_job_per_place_type', type_='unique')
        batch_op.create_index(batch_op.f('uq_active_job_per_place_type'), ['place_id', 'job_type'], unique=1, sqlite_where=sa.text('is_active = 1'))

    with op.batch_alter_table('hitlist_suggestions', schema=None) as batch_op:
        batch_op.drop_index('ix_hitlist_suggestions_user_created')
        batch_op.drop_index('ix_hitlist_suggestions_resolved_place')
        batch_op.drop_index('ix_hitlist_suggestions_name_city')
        batch_op.drop_index(batch_op.f('ix_hitlist_suggestions_hitlist_suggestions_user_id'))
        batch_op.drop_index(batch_op.f('ix_hitlist_suggestions_hitlist_suggestions_place_name'))

    op.drop_table('hitlist_suggestions')
    with op.batch_alter_table('hitlist_saves', schema=None) as batch_op:
        batch_op.drop_index('ix_hitlist_saves_user_created')
        batch_op.drop_index('ix_hitlist_saves_status')
        batch_op.drop_index('ix_hitlist_saves_place_id')
        batch_op.drop_index(batch_op.f('ix_hitlist_saves_hitlist_saves_user_id'))
        batch_op.drop_index(batch_op.f('ix_hitlist_saves_hitlist_saves_resolution_status'))

    op.drop_table('hitlist_saves')
    with op.batch_alter_table('hitlist_dedup_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hitlist_dedup_keys_hitlist_dedup_keys_user_id'))

    op.drop_table('hitlist_dedup_keys')
    # ### end Alembic commands ###