import type { CommandName } from './commands.js';

const TITLES: Record<CommandName, string> = {
  ask: 'AI answer',
  review: 'AI review',
  summarize: 'AI summary',
  help: 'AI assistant help',
};

export function responseMarker(commentId: number): string {
  return `<!-- crave-ai-source-comment:${commentId} -->`;
}

export function hasProcessedComment(commentBodies: readonly string[], commentId: number): boolean {
  const marker = responseMarker(commentId);
  return commentBodies.some((body) => body.includes(marker));
}

export function formatResponse(content: string, commentId: number, command: CommandName): string {
  return [
    `### ${TITLES[command]}`,
    '',
    content.trim(),
    '',
    "_Generated by the repository's AI assistant. Verify important findings before merging._",
    '',
    responseMarker(commentId),
  ].join('\n');
}
